In [1]:
#!/usr/bin/env pyhon
from __future__ import print_function
from itertools import count
import numpy as np
import torch
import torch.autograd
import torch.nn.functional as F
from torch.autograd import Variable
import matplotlib.pyplot as plt

In [2]:
s = torch.nn.Sigmoid()
input = Variable(torch.randn(2))
print(input)
print(m(input))

tensor([0.7744, 0.1936])
tensor([0.6845, 0.5483])


In [3]:
t=torch.nn.Tanh()
print(t(input))

tensor([0.6495, 0.1913])


In [7]:
m=torch.nn.Hardtanh(-2,2)
input=Variable(torch.randn(2))
print(input)
print(m(input))

tensor([ 2.5991, -0.8791])
tensor([ 2.0000, -0.8791])


In [10]:
m=torch.nn.ReLU()
input=Variable(torch.randn(2))
print(input)
print(m(input))

tensor([ 0.3176, -0.4108])
tensor([0.3176, 0.0000])


In [13]:
loss = torch.nn.MSELoss()
input = Variable(torch.randn(2,5),requires_grad=True)
target=Variable(torch.randn(2,5))
output=loss(input,target)
output.backward()

In [34]:
loss = torch.nn.CrossEntropyLoss()
m=torch.nn.Sigmoid()
input = Variable(torch.randn(2,5),requires_grad=True)
#target=Variable(torch.rand(2))
target=torch.LongTensor(2).random_(2)
output=loss(m(input),target)
output.backward()